sonar.projectKey=tienda-agora-api
sonar.projectName=Tienda Agora API
sonar.projectVersion=2.0.0
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
